title:             Becoming Dapper
email:             austin@shugartonline.com
description:       Insert description here.
author:            Austin Shugart
# baseurl:           "/startbootstrap-clean-blog-jekyll"
# url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  austinglenn
linkedin_username:   austinshugart
instagram_username: ashug19

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
